knowledgeManager:
  splitterType: "semantic" # recursive or semantic
  database: "qdrant" # chroma or qdrant
agent:
  baseUrl: "http://192.168.88.26:1234/v1" #
  model: "nvidia/nemotron-3-nano"
supervisor:
  baseUrl: "http://192.168.88.26:1234/v1"
  model: "nvidia/nemotron-3-nano"
  forceReflectionIssues: true
tasksModel:
  baseUrl: "http://192.168.88.26:1234/v1"
  model: "qwen/qwen3-1.7b"
debugOutput: true
