services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant:/qdrant/storage
      
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    ports:
      - 3000:8080
    environment:
      OLLAMA_BASE_URL: http://192.168.88.26:1234/v1
    volumes:
      - ./webui:/app/backend/data